apiVersion: v1
kind: Service
metadata:
  name: {{.Values.service.service_name }}
  namespace: {{.Release.Namespace }}
  labels:
    app: {{.Values.service.service_label }}
spec:
  type: {{.Values.service.service_type }}
  selector:
    app: {{.Values.deployment.pod_label }}
  ports:
    - name: http
      port: {{.Values.service.port }}
      targetPort: {{.Values.service.targetport }}
      nodePort: {{.Values.service.nodeport }}
